---
title: "spatial_1"
output: html_document
date: "2024-03-14"
---

# Install and load the tmap and spDataLarge packages (available from GitHub). Load and review the pol_pres15 dataset on the Polish Presidential election in 2015
```{r}
# install required packages
install.packages("tmap", repos = "https://r-tmap.github.io/tmap/", type = "source")
install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")

library(tmap)
library(spDataLarge)

# load the tmap and spDataLarge packages
pacman::p_load(
  ggplot2,
  spatstat,
  spatialreg,
  spgwr,
  spdep,
  adehabitatHR,
  googleway,
  gmapsdistance,
  leaflet,
  dismo,
  raster,
  sp,
  leaflet,
  tmap,
  foreign,
  sf,
  terra,
  RColorBrewer,
  stargazer,
  rmapshaper
)

# load the dataset
data("pol_pres15")

summary(pol_pres15)

```

# One visualization should compare the support for Komorowski and Duda
```{r}
# setting color palette
display.brewer.all()

# first round vote share of komorowski and duda on choropleth
tm_shape(pol_pres15) + 
  tm_fill("I_Duda_share", palette = "RdYlGn", style = "equal", n = 2, breaks = c(0, 0.49, 1), 
          labels = c("Komoroski", "Duda")) + 
  tm_borders(alpha = 0.5, col = "white") + 
  tm_compass() + 
  tm_layout(title = "First Round Vote Share of Komorowski and Duda", 
            legend.text.size = 1, legend.title.size = 0.01, 
            legend.position = c("left", "bottom"), legend.title.color = "white", frame = FALSE)

# runoff vote share of komorowski and duda on choropleth
tm_shape(pol_pres15) + 
  tm_fill("II_Duda_share", palette = "RdYlGn", style = "equal", n = 2, alpha = 1, breaks = c(0, 0.49, 1), 
          labels = c("Komoroski", "Duda")) + 
  tm_borders(alpha = 0.5, col = "white") + 
  tm_dots("types", palette = "BrBG") +
  tm_compass() + 
  tm_layout(title = "Runoff Round Vote Share of Komorowski and Duda", 
            legend.text.size = 1, legend.title.size = 0.01, 
            legend.position = c("left", "bottom"), legend.title.color = "white", frame = FALSE)

# percentage of vote share by each candidate
tm_shape(pol_pres15) + 
  tm_fill("II_Duda_share", palette = "RdYlGn", style = "equal", n = 10, breaks = c(0, 0.49, 1), 
          labels = c("Komoroski (91-100)","Komoroski (90-81)", "Komoroski (80-71)","Komoroski (70-61)","Komoroski (60-51)", "Duda (51-60)","Duda (61-70)","Duda (71-80)","Duda (81-90)","Duda (91-100)")) + 
  tm_borders(alpha = 0.5, col = "black") + 
  tm_compass() + 
  tm_layout(title = "Percentage of Vote Share by Each Candidate", 
            legend.text.size = 0.55, legend.title.size = 0.01, 
            legend.position = c("left", "bottom"), legend.title.color = "white", frame = FALSE)

```


# One visualization should investigate possible issues with postal voting envelopes
```{r}
# correlation of unused voting papers
plot(II_unused_voting_papers ~ II_of_which_voting_papers_taken_from_voting_envelopes, 
     data = pol_pres15, 
     xlab = "Voting papers taken from voting envelopes", 
     ylab = "Unused Voting Papers", 
     col = "blue")

plot(II_unused_voting_papers ~ II_voting_papers_taken_from_ballot_box, 
     data = pol_pres15, 
     xlab = "Voting papers taken from Ballot Box", 
     ylab = "Unused Voting Papers", 
     col = "red")

# correlation of invalid votes
plot(II_invalid_votes ~ II_of_which_voting_papers_taken_from_voting_envelopes, data = pol_pres15, 
     ylab = "Number of Invalid Votes", 
     xlab = "Voting papers taken from voting envelopes", 
     col = "blue")

plot(II_invalid_votes ~ II_voting_papers_taken_from_ballot_box, 
     data = pol_pres15, 
     ylab = "Number of Invalid Votes", 
     xlab = "Voting papers taken from Ballot Box", 
     col = "red")

```

